### ISSUE TITLE
Add current/future data access policies

### ISSUE THREAD

**Issue by stekhoven** [ETH-NEXUS/tu-pro_website#7]
On the page data access (`data.md`) the current practice for data availability and the future plans for data access should be described. 

In addition, a contact for questions regarding data access questions would make sense - @nctoussaint ?

**Comment by nctoussaint** [comment]
Since these processes have not been defined and I wouldn't want anybody to contact us just now, I would put
"The data will be made available. Please check back later."

**Comment by stekhoven** [comment]
I included this - however, it is not sure whether this will be sufficient to hold off people from contacting us. We will see.
